name: google_doc_clone
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  routemaster: ^1.0.1
  flutter_riverpod: ^2.5.1
  google_sign_in: ^6.2.1
  http: ^1.2.2
  shared_preferences: ^2.3.2
  flutter_quill: ^10.8.2
  socket_io_client: ^1.0.2
  together_ai_sdk: ^2.0.2
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/docs-logo.png
    - assets/images/g-logo-2.png
