name: Deploy Flutter Web to EC2

on:
  push:
    branches:
      - main # or your deployment branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    env:
      EC2_IP: 3.87.122.251
      SSH_USER: ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: ./

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
    
      - name: Add EC2 Host to Known Hosts
        run: |
          ssh-keyscan -H $EC2_IP >> ~/.ssh/known_hosts

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3' # Use your Flutter version

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web

      - name: Deploy to EC2
        working-directory: ./build/web
        run: |
          scp -r ./* ubuntu@3.87.122.251:/var/www/html/
          ssh $SSH_USER@$EC2_IP 'sudo systemctl restart nginx'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
