name: Deploy Server and Restart with PM2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        path: ./server

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
    
    - name: Add EC2 Host to Known Hosts
      run: |
        ssh-keyscan -H 3.84.93.148 >> ~/.ssh/known_hosts

    - name: Sync Server Folder to EC2
      working-directory: ./server
      run: |
        scp ./* ubuntu@3.84.93.148:/home/ubuntu
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

    - name: Restart Node Server with PM2
      run: |
        ssh ubuntu@3.84.93.148 "
        cd /home/ubuntu/server && npm install && 
        pm2 stop all || true && 
        pm2 start npm -- start && 
        pm2 save"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
